name: Deploy to Hugging Face Spaces

on:
  push:
    branches:
      - main
      - master
    paths:
      - 'app.py'
      - 'requirements.txt'
      - 'tinyllama-poetry/**'
      - '.github/workflows/**'
  workflow_dispatch: # Allow manual trigger

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        lfs: true
    
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install huggingface_hub
    
    - name: Validate required files
      run: |
        echo "Checking required files..."
        if [ ! -f "app.py" ]; then
          echo "❌ app.py not found"
          exit 1
        fi
        if [ ! -f "requirements.txt" ]; then
          echo "❌ requirements.txt not found"
          exit 1
        fi
        if [ ! -d "tinyllama-poetry" ]; then
          echo "❌ tinyllama-poetry directory not found"
          exit 1
        fi
        echo "✅ All required files found"
    
    - name: Prepare deployment files
      run: |
        # Copy README for HF Spaces if it exists
        if [ -f "hf_spaces_README.md" ]; then
          cp hf_spaces_README.md README.md
          echo "✅ Using HF Spaces README"
        fi
        
        # List files to be deployed
        echo "Files to deploy:"
        ls -la
        
        echo "LoRA adapter contents:"
        ls -la tinyllama-poetry/
    
    - name: Deploy to Hugging Face Spaces
      env:
        HF_TOKEN: ${{ secrets.HF_TOKEN }}
        HF_USERNAME: ${{ secrets.HF_USERNAME }}
        SPACE_NAME: ${{ secrets.SPACE_NAME }}
      run: |
        python -c "
        import os
        from huggingface_hub import HfApi, create_repo
        from pathlib import Path
        import shutil
        
        # Configuration
        token = os.environ.get('HF_TOKEN')
        username = os.environ.get('HF_USERNAME')
        space_name = os.environ.get('SPACE_NAME', 'chinese-poetry-generator')
        repo_id = f'{username}/{space_name}'
        
        print(f'Deploying to: {repo_id}')
        
        # Initialize HF API
        api = HfApi(token=token)
        
        try:
            # Skip space creation - assume it exists
            print('Using existing Space...')
            print('✅ Space found')
            
            # Upload files
            files_to_upload = [
                'app.py',
                'requirements.txt',
                'README.md'
            ]
            
            # Upload main files
            for file in files_to_upload:
                if Path(file).exists():
                    print(f'Uploading {file}...')
                    api.upload_file(
                        path_or_fileobj=file,
                        path_in_repo=file,
                        repo_id=repo_id,
                        repo_type='space',
                        token=token
                    )
                    print(f'✅ {file} uploaded')
            
            # Upload LoRA adapter directory
            if Path('tinyllama-poetry').exists():
                print('Uploading LoRA adapter...')
                api.upload_folder(
                    folder_path='tinyllama-poetry',
                    repo_id=repo_id,
                    repo_type='space',
                    path_in_repo='tinyllama-poetry',
                    token=token
                )
                print('✅ LoRA adapter uploaded')
            
            print(f'🚀 Deployment complete! Visit: https://huggingface.co/spaces/{repo_id}')
            
        except Exception as e:
            print(f'❌ Deployment failed: {e}')
            exit(1)
        "
    
    - name: Post-deployment validation
      env:
        HF_USERNAME: ${{ secrets.HF_USERNAME }}
        SPACE_NAME: ${{ secrets.SPACE_NAME }}
      run: |
        space_name="${SPACE_NAME:-chinese-poetry-generator}"
        echo "🎉 Deployment completed successfully!"
        echo "📍 Your app is available at: https://huggingface.co/spaces/$HF_USERNAME/$space_name"
        echo "⏳ Note: First startup may take 2-3 minutes to download the model"